name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on: push

env:
  uniqueWorkspaceId: /u/wfezzan/builds-github/${{ github.repository }}/${{ github.ref_name }}/build_b${{github.run_number }} # adding a b to before the number,
    # to avoid an error caused by repeated build numbers 
  branch : ${{ github.ref_name }} 
  application: ${{ github.event.repository.name }}
  pipelineType: ${{ inputs.pipelineType }}
  packageName: ${{github.run_id}}
  zosHostname: 9.76.61.15
  zosSFTPUser: WFEZZAN@10.3.20.34
  WD_ARTIFACTS: /u/wfezzan/wazi-deploy-artifacts
  WD_SAMPLES: /var/wazi-deploy-samples/cics-genapp/wazideploy-samples/python/dbb
  PACKAGE_BUILD_OUTPUTS_FOLDER: /var/dbb-pipelineBackend/dbb/Pipeline/PackageBuildOutputs
  ARTIFACTORY_STATIC_BUILD_NAME: cics-genapp-wd-static-build



jobs:
  Setup:
    runs-on: self-hosted
    steps:
      - name: Clone Repo to z/OS Unix System Services
        run: |
           ssh ${{ env.zosSFTPUser}} ". ./.profile && gitClone.sh -w ${{ env.uniqueWorkspaceId }} -r  https://${{ secrets.eole59_token }}github.com/${{ github.repository }}.git -b${{ env.branch }}" 
          
  Build:
    needs: Setup
    runs-on: self-hosted
    steps:
      - name: Build Application
        run: | 
            ssh ${{ env.zosSFTPUser}} ". ./.profile && dbbBuild.sh -w ${{ env.uniqueWorkspaceId }} -a ${{env.application}} -b ${{ env.branch }} -p build -t --impactBuild -v"
      - name: Prepare logs
        run: | 
          ssh ${{ env.zosSFTPUser}} ". ./.profile && prepareLogs.sh -w ${{ env.uniqueWorkspaceId }}" 
          rm -rf "${{ runner.temp }}/build-logs" 
          mkdir "${{ runner.temp }}/build-logs" 
          sftp ${{ env.zosSFTPUser}}:${{ env.uniqueWorkspaceId }}/*.tar "\"${{ runner.temp }}/build-logs\""
          tar -xvf "${{ runner.temp }}/build-logs/logs.tar" -C "${{ runner.temp }}/build-logs"
      - name: Upload build logs
        uses: actions/upload-artifact@v4
        with:
                name: build_logs_${{github.run_number }}                        # Name used for artifact when it is uploaded
                path: ${{ runner.temp }}/build-logs                             # Path to build logs artifacts
                retention-days: 1
   
  Package:
        needs: Build
        runs-on: self-hosted
        steps:
          - name: Create Package and publish to Nexus
            run: |
                ssh ${{env.zosSFTPUser}} ". ./.profile && cd ${WD_ARTIFACTS}"
                ssh ${{env.zosSFTPUser}} ". ./.profile && python  $WD_SAMPLES/dbb_prepare_local_folder.py --dbbBuildResult ${{ env.uniqueWorkspaceId }}/logs/BuildReport.json --workingFolder ${{ env.uniqueWorkspaceId }}/package"     
                ssh ${{env.zosSFTPUser}} ". ./.profile && /u/wfezzan/dbb-v3/bin/groovyz $PACKAGE_BUILD_OUTPUTS_FOLDER/PackageBuildOutputs.groovy --workDir ${{ env.uniqueWorkspaceId }}/logs -p -ad ${{env.application}} -v branch-${{ env.branch }}/pipeline-${{github.run_number }}/${{env.application}}.tar  -aprop /u/wfezzan/builds/appArtifactRepository.properties" 
          - name: Create Package locally
            run: ssh ${{env.zosSFTPUser}} ". ./.profile && /u/wfezzan/dbb-v3/bin/groovyz $PACKAGE_BUILD_OUTPUTS_FOLDER/PackageBuildOutputs.groovy --workDir ${{ env.uniqueWorkspaceId }}/logs --tarFileName ${{env.application}}-${{github.run_number }}.tar --application ${{env.application}} --addExtension --branch main --generateWaziDeployAppManifest --versionName v1 --verbose"

   
  Deploy-integration:
        needs: Package
        runs-on: self-hosted
        steps:
          - name: Generate deployment plan 
            run: ssh ${{ env.zosSFTPUser}} ". ./.profile && wazideploy-generate.sh -w ${{ env.uniqueWorkspaceId }}} -m /u/wfezzan/wazi-deploy-artifacts/deploy-method-cics.yaml -p /u/wfezzan/wazi-deploy-artifacts/github/deploymentPlan-${{github.run_number }} -r /u/wfezzan/wazi-deploy-artifacts/github/deploymentPlanReport-${{github.run_number }} -i ${{ env.uniqueWorkspaceId }}/logs/${{env.application}}-${{github.run_number }}.tar"
             
   
   
             
                
